In [1]:
import numpy as np
import pandas as pd
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv("/users/raunakchhabra/54339-104884-bundle-archive/HAM10000_metadata.csv")

In [4]:
data.head()

     lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

In [5]:
data.tail()

         lesion_id      image_id     dx dx_type   age     sex localization
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

In [6]:
data.sex = [1 if each == 'female' else 0 for each in data.sex]

In [7]:
data.dx = [1 if each == 'bkl' or each == 'nv' or each == 'df' else 0 for each in data.dx]

In [8]:
data['age'].dropna()

0        80.0
1        80.0
2        80.0
3        80.0
4        75.0
         ...
10010    40.0
10011    40.0
10012    40.0
10013    80.0
10014    70.0
Name: age, Length: 9958, dtype: float64

In [9]:
data = data.dropna()

In [10]:
data['localization'] = pd.Categorical(data['localization'])
new_categ = pd.get_dummies(data['localization'],prefix ='local')
newdf = pd.concat([data,new_categ],axis=1)

In [11]:
newdf.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_face,local_foot,local_genital,local_hand,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
newdf.tail()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_face,local_foot,local_genital,local_hand,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity
10010,HAM_0002867,ISIC_0033084,0,histo,40.0,0,abdomen,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10011,HAM_0002867,ISIC_0033550,0,histo,40.0,0,abdomen,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10012,HAM_0002867,ISIC_0033536,0,histo,40.0,0,abdomen,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10013,HAM_0000239,ISIC_0032854,0,histo,80.0,0,face,0,0,0,...,1,0,0,0,0,0,0,0,0,0
10014,HAM_0003521,ISIC_0032258,0,histo,70.0,1,back,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [13]:
data = newdf

In [14]:
data.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_face,local_foot,local_genital,local_hand,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
data['dx_type'] = pd.Categorical(data['dx_type'])
new_categ_df = pd.get_dummies(data['dx_type'],prefix ='dx_type')
new_data =  pd.concat([data,new_categ_df],axis=1)

In [16]:
new_data.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [17]:
new_data_frame = pd.concat([data,new_categ_df],axis=1)
data = new_data_frame
data.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [18]:
data = data.drop(['localization','lesion_id','image_id','dx_type'],axis=1)

In [19]:
data.head()

,dx,age,sex,local_abdomen,local_acral,local_back,local_chest,local_ear,local_face,local_foot,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
0,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
2,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,1,75.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [20]:
data.tail()

,dx,age,sex,local_abdomen,local_acral,local_back,local_chest,local_ear,local_face,local_foot,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
10010,0,40.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10011,0,40.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10012,0,40.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10013,0,80.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
10014,0,70.0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
x = data.drop('dx',axis=1)
y = data['dx']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)

In [26]:
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [27]:
y_pred = classifier.predict(x_test)

In [28]:
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)

In [29]:
print(cm)

[[526   6]
 [988 970]]